### ISSUE TITLE
Compatibility with exist 5.2.0

### ISSUE THREAD

**Issue by ilpint** [eXist-db/xquery-versioning-module#38]
**Describe the bug**
xquery-versioning-module maybe is not compatible with Exist 5.2.0

**Expected behavior**
Get the module working with Exist 5.2.0

**To Reproduce**
Sorry not beeing able to automate a test, but to reproduce:

1 Install exist 5.2.0 downloading exist-installer-5.2.0.jar
2 Install xquery-versioning-module 1.1.5 with Package Manager 
(then copy manually the jars in existhome/lib, the install procedure also need some fix)
3 create a sample collection with exide, in /db/apps/sample containing an xml
4 save the simplest collection.conf as per documentation
5 restart existdb
6 update the file with exide: success, the .base file is copied into the /db/system/versions/db/apps/sample 
7 update the file again: fail , need a restart of existdb to continue 
8 after restart, every time you try to save even another file into the sample collection you get also an error from exide, not easy to read in the screenshot, can't shrink the window.

![Screenshot from 2020-08-08 18-09-47](https://user-images.githubusercontent.com/6804511/89714950-717a6f00-d9a2-11ea-8682-dfead7659c00.png)

Anyway the error is reported in exist.log:
`
Caused by: java.lang.NoSuchMethodError: org.exist.collections.Collection.getLock()Lorg/exist/storage/lock/Lock;
        at org.exist.versioning.VersioningTrigger.getVersionsCollection(VersioningTrigger.java:454) ~[xquery-versioning-module-1.1.5.jar:1.1.5]
        at org.exist.versioning.VersioningTrigger.before(VersioningTrigger.java:259) ~[xquery-versioning-module-1.1.5.jar:1.1.5]
`

Looking at the org.exist.collections.Collection code, it seems that getLock is no more defined, but still called at line 454 in VersioningTrigger.java, after the versions collection creation.

**Context**
 - OS: ubuntu 18.0.4
 - eXist-db Version: [5.2.0]
 - Java Version: [openjdk version "1.8.0_265"]
-  App Version: [1.1.5]

**Additional context**
- How is eXist-db installed? exist-installer-5.2.0.jar
- Custom changes in `conf.xml`

`<custom-filter class="org.exist.versioning.VersioningFilter"/>`

`<module uri="http://exist-db.org/xquery/versioning" class="org.exist.versioning.xquery.VersioningModule"/>`

- collection.conf
`<collection xmlns="http://exist-db.org/collection-config/1.0">
    <triggers>
        <trigger event="create,update,delete" class="org.exist.versioning.VersioningTrigger">
            <parameter name="overwrite" value="yes"/>
        </trigger>
    </triggers>    
</collection>`
